version: '3.5'

services:
  nulscommunity:
    container_name: nulscommunity
    build:
      context: .
      dockerfile: .docker/production.dockerfile
    ports:
      - ${PORT}:${EXPOSED_PORT}
    expose:
      - ${EXPOSED_PORT}
    environment:
      - NODE_ENV=production
